@startuml DB Diagram

!theme reddress-lightgreen
skinparam defaultFontName monospaced

title DB Diagram


class "Company" as Com {
  +uuid : UUID
  +name : String
  +createdAt : Date
}

class User {
  +uuid : UUID
  +firstName : String
  +lastName : String
  +email : String
  +createdAt : Date
  +lastUpdatedAt : Date?
}

class "CompanyUser" as ComUser {
  +uuid : UUID
  +companyId : int
  +userId : int
  +createdAt : Date
  +role : Role
  +notificationEnabled : boolean
}

User "0..*" -- "1" ComUser
Com "1..*" *-- "1" ComUser

enum Role {
  OWNER
  ADMIN
  USER
}

ComUser --> Role

class "Issuance" as Iss {
  +uuid : UUID
  +companyId : int
  +amount : double
  +yearlyInterestRate : double
  +createdAt : Date
}

Com "1..*" o-- "1" Iss

class "Token" as Tok {
  +uuid : UUID
  +issuanceId : int
  +externalReference : String
  +creditorFullName : String
  +amount : double
  +createdAt : Date
}

Iss "1..*" o-- "1" Tok

class "Payment" as Pay {
  +uuid : UUID
  +tokenId : int
  +amount : double
  +dueAt : Date
  +paidAt : Date?
}

Tok "1..*" o-- "1" Pay

@enduml
