openapi: 3.1.0

info:
  title: Error
  version: 1.0.0

components:
  schemas:
    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      required:
        - code
        - message
