apis:
  v1:
    root: src/openapi.yaml
  v1_merged:
    root: src/openapi.merged.yaml
rules:
  no-empty-servers: off
  info-license: off
  info-license-url: off
  security-defined: off
  operation-4xx-response: off
  operation-operationId: off
theme:
  openapi:
    pagination: section
    layout: stacked
    showConsole: true
    sideNavStyle: summary-only
    pathInMiddlePanel: true
    expandDefaultRequest: false
    expandDefaultResponse: false
    sortOperationsAlphabetically: true
    theme:
      colors:
        primary:
          main: '#0065FB'
